### PR TITLE
✨ admin/student page: login and register

### LINKED ISSUE #227: student/admin: login en registration
- [x] login page conforms to the design for mobile and desktop
- [x] redirect to page is different for different user roles
- [x] registration page

### PR DESCRIPTION
**Pull request by eliasnijs**
closes #227.

### CODE REVIEW

**Comment by milachae** [comment]
image
@eliasnijs 
Something went wrong with the links. I tried to log in with an admin account and I got a 404.

**Comment by milachae** [comment]
A cell phone number is just 10 numbers.

image

**Comment by eliasnijs** [comment]
> image
> @eliasnijs 
> Something went wrong with the links. I tried to log in with an admin account and I got a 404.

Yes, the page names still need to be updated. Mire specifically planning now should become dashboard. Login already goes to the correct page.

**Comment by eliasnijs** [comment]
> A cell phone number is just 10 characters.
> 
> image

Depends on which format... I included country code.

**Comment by eliasnijs** [comment]
I will add something making the format used for phone numbers clear on the login page.

**Comment by milachae** [comment]
@eliasnijs 
* In the meeting of 11/05, there was decided that you will make the services for the user. I suppose that this PR is not yet finished?
* The Home Button (logo Dr.trottoir) leads to a wrong 404 page.
* The Automatic redirect to /admin/dashboard is good, but it is really annoying that this is a 404 page now. Testing something is now really annoying because it always redirects to that 404.

**Comment by eliasnijs** [comment]
closes #296

**Comment by eliasnijs** [comment]
@milachae Register service is implemented now.

**Review by milachae — APPROVED** [review]
This works, just fix the merge conflicts.

**Pull request merged**
